language: node_js

node_js:
- '8.10'

env:
  global:
    - SLS_DEBUG=true

before_install:
  - npm i -g serverless

install:
  - npm i
  - serverless env --attribute GOOGLE_API_KEY --value $GOOGLE_API_KEY --stage dev
  - serverless env --attribute W3W_API_KEY --value $W3W_API_KEY --stage dev
  - serverless env --attribute OPCD_API_KEY --value $OPCD_API_KEY --stage dev
  - serverless env --attribute GOOGLE_API_KEY --value $GOOGLE_API_KEY --stage prod
  - serverless env --attribute W3W_API_KEY --value $W3W_API_KEY --stage prod
  - serverless env --attribute OPCD_API_KEY --value $OPCD_API_KEY --stage prod

after_script: ./deploy.sh
